version: '3'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]  # Persist
    volumes:
      - redis:/data

  web:
    build: .
    ports:
      - 5000:80
    depends_on:
      - redis
    environment:
      FLASK_APP: app
      FLAST_ENV: production
      REDIS_URL: redis://redis/0
    restart: unless-stopped

volumes:
  redis:
